services:
  - type: web
    name: your2ndride-chat
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://your2ndride.vercel.app
    plan: free
